### ISSUE TITLE
multiple templates

### ISSUE THREAD

**Issue by MareoRaft** [haldunanil/create-reactjs-component#2]
It seems that I need a different template for different types of components.  For example, if I have a "container" component which hooks up to a Redux store, then I need a template for that.  If I have "presentational/functional" component that has little more than a render function, then I need a template for that.

I have added such a `--template` option to my fork of the repo (https://github.com/MareoRaft/create-react-component), which allows you to choose from a number of templates.

If you think other people would benefit from this feature, then I would be happy to open a pull request.  Just let me know.

**Comment by haldunanil** [comment]
Yeah, this sounds good, go ahead and open a PR! :)

**Comment by MareoRaft** [comment]
Please see PR #3 .  You may want to try it out on your machine once to verify it works as you like.

**Comment by haldunanil** [comment]
Merged!
